
FIND_PATH(OPENSSL_INCLUDE_DIR openssl/ssl.h
/usr/include/
/usr/local/include/
)

FIND_LIBRARY(OPENSSL_LIBRARY NAMES ssl
PATHS
/usr/lib
/usr/local/lib
)

IF(OPENSSL_INCLUDE_DIR AND OPENSSL_LIBRARY)
   SET(OPENSSL_FOUND TRUE)
ENDIF(OPENSSL_INCLUDE_DIR AND OPENSSL_LIBRARY)


IF(OPENSSL_FOUND)
   IF(NOT OPENSSL_FIND_QUIETLY)
      MESSAGE(STATUS "Found OpenSSL: ${OPENSSL_LIBRARY}")
   ENDIF(NOT OPENSSL_FIND_QUIETLY)
ELSE(OPENSSL_FOUND)
   IF(OPENSSL_FIND_REQUIRED)
      MESSAGE(SEND_ERROR "Could not find OpenSSL")
   ENDIF(OPENSSL_FIND_REQUIRED)
ENDIF(OPENSSL_FOUND)
