IF (CACHED_ZLIB)

  # in cache already
  IF ("${CACHED_ZLIB}" STREQUAL "YES")
    SET(ZLIB_FOUND TRUE)
  ENDIF ("${CACHED_ZLIB}" STREQUAL "YES")

ELSE (CACHED_ZLIB)

  FIND_PATH(ZLIB_INCLUDE_DIR zlib.h
   /usr/include
   /usr/local/include
  )

  FIND_LIBRARY(ZLIB_LIBRARY NAMES z zlib
  PATHS
   /usr/lib
   /usr/local/lib
  )

  IF (ZLIB_INCLUDE_DIR)
     SET(ZLIB_FOUND TRUE)
     SET(CACHED_ZLIB "YES")
  ELSE (ZLIB_INCLUDE_DIR)
     SET(CACHED_ZLIB "NO")
  ENDIF (ZLIB_INCLUDE_DIR)

  IF (ZLIB_FOUND)
     IF (NOT ZLIB_FIND_QUIETLY)
        MESSAGE(STATUS "Found Z: ${ZLIB_LIBRARY}")
     ENDIF (NOT ZLIB_FIND_QUIETLY)
  ELSE (ZLIB_FOUND)
     IF (ZLIB_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find z library")
     ENDIF (ZLIB_FIND_REQUIRED)
  ENDIF (ZLIB_FOUND)

  SET(CACHED_ZLIB ${CACHED_ZLIB} CACHE INTERNAL "If zlib was checked")
  MARK_AS_ADVANCED(ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

ENDIF (CACHED_ZLIB)
