# - Try to find the Kdcraw library using cmake pkg_check_modules

if (KDCRAW_INCLUDEDIR AND KDCRAW_LIBRARIES)
    # in cache already
    SET(KDCRAW_FOUND TRUE)
else (KDCRAW_INCLUDEDIR AND KDCRAW_LIBRARIES)
    if(NOT WIN32)
        find_package(PkgConfig REQUIRED)
        if (Kdcraw_FIND_REQUIRED)
            pkg_check_modules(KDCRAW REQUIRED libkdcraw>=0.2.0)
        else (Kdcraw_FIND_REQUIRED)
            pkg_check_modules(KDCRAW libkdcraw>=0.2.0)
        endif (Kdcraw_FIND_REQUIRED)
    else(NOT WIN32)
        set(KDCRAW_FOUND TRUE)
    endif(NOT WIN32)
    if(KDCRAW_FOUND)
        set(KDCRAW_DEFINITIONS ${KDCRAW_CFLAGS})
        if (NOT Kdcraw_FIND_QUIETLY)
            message(STATUS "Found libkdcraw: ${KDCRAW_LIBRARIES}")
        endif (NOT Kdcraw_FIND_QUIETLY)
    endif (KDCRAW_FOUND)
endif (KDCRAW_INCLUDEDIR AND KDCRAW_LIBRARIES)
