# - Try to find the Kexiv2 library using cmake pkg_check_modules

if (KEXIV2_INCLUDEDIR AND KEXIV2_LIBRARIES)
    # in cache already
    SET(KEXIV2_FOUND TRUE)
else (KEXIV2_INCLUDEDIR AND KEXIV2_LIBRARIES)
    if(NOT WIN32)
        find_package(PkgConfig REQUIRED)
        if (Kexiv2_FIND_REQUIRED)
            pkg_check_modules(KEXIV2 REQUIRED libkexiv2>=0.2.0)
        else (Kexiv2_FIND_REQUIRED)
            pkg_check_modules(KEXIV2 libkexiv2>=0.2.0)
        endif (Kexiv2_FIND_REQUIRED)
    else(NOT WIN32)
        set(KEXIV2_FOUND TRUE)
    endif(NOT WIN32)
    if(KEXIV2_FOUND)
        set(KEXIV2_DEFINITIONS ${KEXIV2_CFLAGS})
        if (NOT Kexiv2_FIND_QUIETLY)
            message(STATUS "Found libkexiv2: ${KEXIV2_LIBRARIES}")
        endif (NOT Kexiv2_FIND_QUIETLY)
    endif (KEXIV2_FOUND)
endif (KEXIV2_INCLUDEDIR AND KEXIV2_LIBRARIES)
