
FIND_PATH(JASPER_INCLUDE_DIR jasper/jasper.h
/usr/include
/usr/local/include
)

FIND_LIBRARY(JASPER_LIBRARY NAMES jasper
PATHS
/usr/lib
/usr/local/lib
)


IF(JASPER_INCLUDE_DIR AND JASPER_LIBRARY)
   SET(JASPER_FOUND TRUE)
ENDIF(JASPER_INCLUDE_DIR AND JASPER_LIBRARY)


IF(JASPER_FOUND)
   IF(NOT JASPER_FIND_QUIETLY)
      MESSAGE(STATUS "Found jasper: ${JASPER_LIBRARY}")
   ENDIF(NOT JASPER_FIND_QUIETLY)
ELSE(JASPER_FOUND)
   IF(JASPER_FIND_REQUIRED)
      MESSAGE(SEND_ERROR "Could not find jasper library")
   ENDIF(JASPER_FIND_REQUIRED)
ENDIF(JASPER_FOUND)
