
FIND_PATH(FAM_INCLUDE_DIR fam.h
/usr/include
/usr/local/include
)

FIND_LIBRARY(FAM_LIBRARY NAMES fam
PATHS
/usr/lib
/usr/local/lib
)


IF(FAM_INCLUDE_DIR)
   SET(FAM_FOUND TRUE)
ENDIF(FAM_INCLUDE_DIR)


IF(FAM_FOUND)
   IF(NOT FAM_FIND_QUIETLY)
      MESSAGE(STATUS "Found fam: ${FAM_LIBRARY}")
   ENDIF(NOT FAM_FIND_QUIETLY)
ELSE(FAM_FOUND)
   IF(FAM_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find fam library")
   ENDIF(FAM_FIND_REQUIRED)
ENDIF(FAM_FOUND)
