
# use pkg-config to get the directories and then use these values
# in the FIND_PATH() and FIND_LIBRARY() calls
INCLUDE(UsePkgConfig)

PKGCONFIG(OpenEXR _OpenEXRIncDir _OpenEXRLinkDir _OpenEXRLinkFlags _OpenEXRCflags)

#PKGCONFIG(libagg _AGGIncDir _AGGLinkDir _AGGLinkFlags _AGGCflags)

FIND_PATH(OPENEXR_INCLUDE_DIR ImfRgbaFile.h
${_OpenEXRIncDir}
${_OpenEXRIncDir}/OpenEXR/
/usr/include
/usr/local/include
)

MESSAGE(STATUS "OPENEXR_INCLUDE_DIR :${OPENEXR_INCLUDE_DIR}")

FIND_LIBRARY(OPENEXR_HALF_LIBRARY NAMES Half
  PATHS
  ${_OPENEXRLinkDir}
  /usr/lib
  /usr/local/lib
)


FIND_LIBRARY(OPENEXR_IEX_LIBRARY NAMES Iex
  PATHS
  ${_OPENEXRLinkDir}
  /usr/lib
  /usr/local/lib
)

FIND_LIBRARY(OPENEXR_IMATH_LIBRARY NAMES Imath
  PATHS
  ${_OPENEXRLinkDir}
  /usr/lib
  /usr/local/lib
)


FIND_LIBRARY(OPENEXR_ILMIMF_LIBRARY NAMES IlmImf 
  PATHS
  ${_OPENEXRLinkDir}
  /usr/lib
  /usr/local/lib
)

MESSAGE(STATUS "OPENEXR_IMATH_LIBRARIES: ${OPENEXR_IMATH_LIBRARY}, OPENEXR_ILMIMF_LIBRARY: ${OPENEXR_ILMIMF_LIBRARY}, OPENEXR_IEX_LIBRARY: ${OPENEXR_IEX_LIBRARY}, OPENEXR_HALF_LIBRARY: ${OPENEXR_HALF_LIBRARY}")

SET( OPENEXR_LIBRARIES ${OPENEXR_HALF_LIBRARY}
	${OPENEXR_IMATH__LIBRARY}...)
IF(OPENEXR_INCLUDE_DIR AND OPENEXR_IMATH_LIBRARY AND OPENEXR_ILMIMF_LIBRARY  AND OPENEXR_IEX_LIBRARY AND OPENEXR_HALF_LIBRARY)
   SET(OPENEXR_FOUND TRUE)
   SET( OPENEXR_LIBRARIES ${OPENEXR_IMATH_LIBRARY} ${OPENEXR_ILMIMF_LIBRARY} ${OPENEXR_IEX_LIBRARY} ${OPENEXR_HALF_LIBRARY})
ENDIF(OPENEXR_INCLUDE_DIR AND OPENEXR_IMATH_LIBRARY AND OPENEXR_ILMIMF_LIBRARY AND OPENEXR_IEX_LIBRARY AND OPENEXR_HALF_LIBRARY)



IF (OPENEXR_FOUND)
  IF (NOT OpenEXR_FIND_QUIETLY)
    MESSAGE(STATUS "Found OPENEXR: ${OPENEXR_LIBRARIES}")
  ENDIF (NOT OpenEXR_FIND_QUIETLY)
ELSE (OPENEXR_FOUND)
  IF (OpenEXR_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find OPENEXR")
  ENDIF (OpenEXR_FIND_REQUIRED)
ENDIF (OPENEXR_FOUND)

MARK_AS_ADVANCED(OPENEXR_INCLUDE_DIR OPENEXR_LIBRARIES)


