# Find if we installed kdebase/runtime.
# Once done this will define
#
#  KDE4RUNTIME_FOUND - system has KDE runtime installed
#  KDE4RUNTIME_INCLUDE_DIR - the KDE runtime include directory
#
# It also sets variables for the following libraries:
#   KDE4RUNTIME_TASKMANAGER_LIBRARY, KDE4RUNTIME_TASKMANAGER_LIBS
#   KDE4RUNTIME_KRUNTIME_LIBRARY, KDE4RUNTIME_KRUNTIME_LIBS
#   KDE4RUNTIME_SOLIDCONTROLIFACES_LIBRARY, KDE4RUNTIME_SOLIDCONTROLIFACES_LIBS
#   KDE4RUNTIME_SOLIDCONTROL_LIBRARY, KDE4RUNTIME_SOLIDCONTROL_LIBS
#   KDE4RUNTIME_PROCESSUI_LIBRARY, KDE4RUNTIME_PROCESSUI_LIBS
#   KDE4RUNTIME_LSOFUI_LIBRARY, KDE4RUNTIME_LSOFUI_LIBS
#   KDE4RUNTIME_PLASMACLOCK_LIBRARY, KDE4RUNTIME_PLASMACLOCK_LIBS
#   KDE4RUNTIME_NEPOMUKQUERYCLIENT_LIBRARY, KDE4RUNTIME_NEPOMUKQUERYCLIENT_LIBS
#   KDE4RUNTIME_NEPOMUKQUERY_LIBRARY, KDE4RUNTIME_NEPOMUKQUERY_LIBS
#   KDE4RUNTIME_KSCREENSAVER_LIBRARY, KDE4RUNTIME_KSCREENSAVER_LIBS
#   KDE4RUNTIME_WEATHERION_LIBRARY, KDE4RUNTIME_WEATHERION_LIBS
#   KDE4RUNTIME_KWINEFFECTS_LIBRARY, KDE4RUNTIME_KWINEFFECTS_LIBS
#   KDE4RUNTIME_KDECORATIONS_LIBRARY, KDE4RUNTIME_KDECORATIONS_LIBS
#   KDE4RUNTIME_KSGRD_LIBRARY, KDE4RUNTIME_KSGRD_LIBS
#   KDE4RUNTIME_KEPHAL_LIBRARY, KDE4RUNTIME_KEPHAL_LIBS
#
# And the following locations:
#   KDE4RUNTIME_LIB_DIR
#   KDE4RUNTIME_LIBEXEC_DIR
#   KDE4RUNTIME_INCLUDE_DIR
#   KDE4RUNTIME_BIN_DIR
#   KDE4RUNTIME_SBIN_DIR
#   KDE4RUNTIME_DATA_DIR
#   KDE4RUNTIME_HTML_DIR
#   KDE4RUNTIME_CONFIG_DIR
#   KDE4RUNTIME_ICON_DIR
#   KDE4RUNTIME_KCFG_DIR
#   KDE4RUNTIME_LOCALE_DIR
#   KDE4RUNTIME_MIME_DIR
#   KDE4RUNTIME_SOUND_DIR
#   KDE4RUNTIME_TEMPLATES_DIR
#   KDE4RUNTIME_WALLPAPER_DIR
#   KDE4RUNTIME_KCONF_UPDATE_DIR
#   KDE4RUNTIME_AUTOSTART_DIR
#   KDE4RUNTIME_XDG_APPS_DIR
#   KDE4RUNTIME_XDG_DIRECTORY_DIR
#   KDE4RUNTIME_SYSCONF_DIR
#   KDE4RUNTIME_MAN_DIR
#   KDE4RUNTIME_INFO_DIR
#   KDE4RUNTIME_DBUS_INTERFACES_DIR
#   KDE4RUNTIME_DBUS_SERVICES_DIR
#   KDE4RUNTIME_SERVICES_DIR
#   KDE4RUNTIME_SERVICETYPES_DIR

# Copyright (c) 2008, Alexander Neundorf, <neundorf@kde.org>
#
# Redistribution and use is allowed according to the terms of the BSD license.
# For details see the accompanying COPYING-CMAKE-SCRIPTS file.

# The find_package() call below loads the file KDE4RuntimeConfig.cmake file.
# This file is created and installed by kdebase/runtime/CMakeLists.txt
# It contains settings for all install location of kdebase/runtime, as e.g.
# KDE4RUNTIME_INCLUDE_DIR, and also variables for all libraries.
# See kdebase/runtime/CMakeLists.txt and kdebase/runtime/KDE4RuntimeConfig.cmake.in 
# for details. Alex


set(_KDE4Runtime_FIND_QUIETLY  ${KDE4Runtime_FIND_QUIETLY})
find_package(KDE4Runtime QUIET NO_MODULE PATHS ${KDE4_LIB_DIR}/KDE4Runtime/cmake )
set(KDE4Runtime_FIND_QUIETLY ${_KDE4Runtime_FIND_QUIETLY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(KDE4Runtime DEFAULT_MSG KDE4Runtime_CONFIG )

