# - Try to find ASPELL
# Once done this will define
#
#  ASPELL_FOUND - system has ASPELL
#  ASPELL_INCLUDE_DIR - the ASPELL include directory
#  ASPELL_LIBRARIES - The libraries needed to use ASPELL
#  ASPELL_DEFINITIONS - Compiler switches required for using ASPELL
#


FIND_PATH(ASPELL_INCLUDE_DIR aspell.h
  /usr/include
  /usr/local/include
)

FIND_LIBRARY(ASPELL_LIBRARIES NAMES aspell aspell-15
  PATHS
  /usr/lib
  /usr/local/lib
)

IF(ASPELL_INCLUDE_DIR AND ASPELL_LIBRARIES)
   SET(ASPELL_FOUND TRUE)
ENDIF(ASPELL_INCLUDE_DIR AND ASPELL_LIBRARIES)

IF(ASPELL_FOUND)
  IF(NOT ASPELL_FIND_QUIETLY)
    MESSAGE(STATUS "Found ASPELL: ${ASPELL_LIBRARIES}")
  ENDIF(NOT ASPELL_FIND_QUIETLY)
ELSE(ASPELL_FOUND)
  IF(ASPELL_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find ASPELL")
  ENDIF(ASPELL_FIND_REQUIRED)
ENDIF(ASPELL_FOUND)

MARK_AS_ADVANCED(ASPELL_INCLUDE_DIR ASPELL_LIBRARIES)
