
FIND_PATH(LIBART_INCLUDE_DIR libart_lgpl/libart.h
/usr/include/libart-2.0
/usr/local/include/libart-2.0
)

FIND_LIBRARY(LIBART_LIBRARY NAMES art_lgpl_2
PATHS
/usr/lib
/usr/local/lib
)


IF(LIBART_INCLUDE_DIR AND LIBART_LIBRARY)
   SET(LIBART_FOUND TRUE)
ENDIF(LIBART_INCLUDE_DIR AND LIBART_LIBRARY)


IF(LIBART_FOUND)
   IF(NOT LIBART_FIND_QUIETLY)
      MESSAGE(STATUS "Found libart: ${LIBART_LIBRARY}")
   ENDIF(NOT LIBART_FIND_QUIETLY)
ELSE(LIBART_FOUND)
   IF(LIBART_FIND_REQUIRED)
      MESSAGE(SEND_ERROR "Could not find libart")
   ENDIF(LIBART_FIND_REQUIRED)
ENDIF(LIBART_FOUND)
