
FIND_PATH(JASPER_INCLUDE_DIR jasper/jasper.h
/usr/include
/usr/local/include
)

FIND_LIBRARY(JASPER_LIBRARY NAMES jasper libjasper
PATHS
/usr/lib
/usr/local/lib
)


IF(JASPER_INCLUDE_DIR AND JASPER_LIBRARY)
   SET(JASPER_FOUND TRUE)
ENDIF(JASPER_INCLUDE_DIR AND JASPER_LIBRARY)


IF(JASPER_FOUND)
   IF(NOT Jasper_FIND_QUIETLY)
      MESSAGE(STATUS "Found jasper: ${JASPER_LIBRARY}")
   ENDIF(NOT Jasper_FIND_QUIETLY)
ELSE(JASPER_FOUND)
   IF(Jasper_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find jasper library")
   ENDIF(Jasper_FIND_REQUIRED)
ENDIF(JASPER_FOUND)
