# - MACRO_ADDITIONAL_CLEAN_FILES(files...)
# MACRO_OPTIONAL_FIND_PACKAGE( <name> [QUIT] )

MACRO(MACRO_ADDITIONAL_CLEAN_FILES)
   GET_DIRECTORY_PROPERTY(_tmp_DIR_PROPS ADDITIONAL_MAKE_CLEAN_FILES )
   
   IF (_tmp_DIR_PROPS)
      SET(_tmp_DIR_PROPS ${_tmp_DIR_PROPS} ${ARGN})
   ELSE (_tmp_DIR_PROPS)
      SET(_tmp_DIR_PROPS ${ARGN})
   ENDIF (_tmp_DIR_PROPS)

   SET_DIRECTORY_PROPERTIES(PROPERTIES ADDITIONAL_MAKE_CLEAN_FILES "${_tmp_DIR_PROPS}")
ENDMACRO(MACRO_ADDITIONAL_CLEAN_FILES)

