// This file is autogenerated by ECMQmlTests.

#include <QQmlEngine>
#include <QtQuickTest>

// This comment is for testing
// As is this one

class Setup : public QObject
{
    Q_OBJECT

public:
    Setup()
    {
    }

public Q_SLOTS:
    void applicationAvailable()
    {
        // This comment is for testing
    }

    void qmlEngineAvailable(QQmlEngine *engine)
    {
        Q_UNUSED(engine)
        // This comment is for testing
    }

    void cleanupTestCase()
    {
        // This comment is for testing
    }
};

QUICK_TEST_MAIN_WITH_SETUP(ecm_qmltests_test, Setup)

#include "ecm_qmltests_test.moc"
